[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[[services]]
name = "app"
dockerfile = ""
buildCommand = "npm install && npm run build"
startCommand = "npm run start"
